### ISSUE TITLE
Error occurred while enabling CookMe v1.8.3 (Is it up to date?)

### ISSUE THREAD

**Issue by amsedal** [timbru31/CookMe#4]
Loading libraries, please wait...
[08:39:39 INFO]: Starting minecraft server version 1.11.2
[08:39:39 INFO]: Loading properties
[08:39:39 INFO]: Default game type: SURVIVAL
[08:39:40 INFO]: This server is running CraftBukkit version git-Spigot-d276ab1-1f6c04c (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

...

[08:40:11 INFO]: [CookMe] Enabling CookMe v1.8.3
[08:40:11 ERROR]: Error occurred while enabling CookMe v1.8.3 (Is it up to date?)
java.lang.NullPointerException
        at de.dustplanet.cookme.CookMe.loadConfig(CookMe.java:150) ~[?:?]
        at de.dustplanet.cookme.CookMe.onEnable(CookMe.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-d276ab1-1f6c04c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by amsedal** [comment]
[08:46:41 ERROR]: Error occurred while enabling CookMe v1.8.4-SNAPSHOT-b76 (Is it up to date?)
java.lang.NullPointerException

**Comment by timbru31** [comment]
Can you give https://ci.dustplanet.de/job/CookMe/77/ a try please?

**Comment by amsedal** [comment]
Yay! It loads! Thank you!

**Comment by timbru31** [comment]
Great. I'll release an update to BukkitDev. Thanks for the quick response
